N1 = int(input('N1: '))
N2 = int(input('N2: '))
print(f'Soma.    : N1 + N2                            = {N1} + {N2} = {N1 + N2}')
print(f'Subtração: N1 - N2                            = {N1} - {N2} = {N1 - N2}')
print(f'Multiplicação: N1 * N2                        = {N1} * {N2} = {N1 * N2}')
print(f'Divisão: N1 / N2                              = {N1} / {N2} = {N1 / N2: .1f}')
print(f'Potência: N1 * N2                            = {N1} * {N2} = {N1 ** N2}')
print(f'Radiciação: N1 * (1/N2)                      = {N1} * {1/N2} = {N1 ** (1/N2): .2f}')
print(f'DIV - QUOCIENTE INTEIRO DA DIVISÃO: N1 DIV N2 = {N1} // {N2} = {N1 // N2}')
print(f'MOD - RESTO INTEIRO DA DIVISÃO.   : N1 MOD N2 = {N1} % {N2} = {N1 % N2}')